# Copyright (c) 2026 Microsoft Corporation. All rights reserved.
# SPDX-License-Identifier: MIT
"""Unit tests for the VEX drafting gate (vex_gate)."""

from __future__ import annotations

import vex_gate

DETECTION_BODY = """\
## VEX detection: untriaged vulnerabilities

| Vulnerability | Aliases | Package | Source | Severity | Current VEX status |
|---------------|---------|---------|--------|----------|--------------------|
| GHSA-69w3-r845-3855 | CVE-2026-1839 | transformers@4.57.6 | uv.lock | 7.8 | none |
| PYSEC-2025-217 | CVE-2025-14929 | transformers@4.57.6 | uv.lock | 7.8 | none |

_Generated by the VEX Detection workflow._
"""


def test_parse_excludes_header_and_separator() -> None:
    ids = vex_gate.parse_finding_ids(DETECTION_BODY)
    assert ids == ["GHSA-69w3-r845-3855", "PYSEC-2025-217"]
    assert "Vulnerability" not in ids
    assert not any(set(i) == {"-"} for i in ids)


def test_parse_dedupes_preserving_order() -> None:
    body = (
        "| CVE-2024-1 | a | p | s | 1 | none |\n"
        "| CVE-2024-1 | a | p | s | 1 | none |\n"
        "| GHSA-aaaa-bbbb-cccc | a | p | s | 1 | none |\n"
    )
    assert vex_gate.parse_finding_ids(body) == [
        "CVE-2024-1",
        "GHSA-aaaa-bbbb-cccc",
    ]


def test_parse_ignores_non_table_and_non_id_rows() -> None:
    assert vex_gate.parse_finding_ids("no table here") == []
    assert vex_gate.parse_finding_ids("| not-an-id | x |") == []


def _doc(*pairs: tuple[str, str]) -> dict:
    return {
        "statements": [
            {"vulnerability": {"name": name}, "status": status}
            for name, status in pairs
        ]
    }


def test_all_terminal_true_when_every_finding_terminal() -> None:
    doc = _doc(("GHSA-1", "not_affected"), ("PYSEC-1", "fixed"))
    assert vex_gate.all_terminal(doc, ["GHSA-1", "PYSEC-1"]) is True


def test_all_terminal_false_when_one_missing() -> None:
    doc = _doc(("GHSA-1", "not_affected"))
    assert vex_gate.all_terminal(doc, ["GHSA-1", "PYSEC-1"]) is False


def test_all_terminal_false_when_one_non_terminal() -> None:
    doc = _doc(("GHSA-1", "not_affected"), ("PYSEC-1", "under_investigation"))
    assert vex_gate.all_terminal(doc, ["GHSA-1", "PYSEC-1"]) is False


def test_all_terminal_empty_findings_is_false() -> None:
    assert vex_gate.all_terminal(_doc(("GHSA-1", "fixed")), []) is False


def test_all_terminal_uses_exact_match_not_substring() -> None:
    # CVE-2024-1 must NOT be considered covered by CVE-2024-100.
    doc = _doc(("CVE-2024-100", "not_affected"))
    assert vex_gate.all_terminal(doc, ["CVE-2024-1"]) is False


def test_all_terminal_matches_via_aliases() -> None:
    doc = {
        "statements": [
            {
                "vulnerability": {"name": "CVE-2026-1839", "aliases": ["GHSA-1"]},
                "status": "not_affected",
            }
        ]
    }
    assert vex_gate.all_terminal(doc, ["GHSA-1"]) is True


def test_evaluate_proceeds_when_no_document() -> None:
    assert vex_gate.evaluate(DETECTION_BODY, None) is True


def test_evaluate_skips_when_no_findings() -> None:
    assert vex_gate.evaluate("no findings", _doc(("GHSA-1", "fixed"))) is False


def test_evaluate_skips_when_all_terminal() -> None:
    doc = _doc(("GHSA-69w3-r845-3855", "not_affected"), ("PYSEC-2025-217", "fixed"))
    assert vex_gate.evaluate(DETECTION_BODY, doc) is False


def test_evaluate_proceeds_when_some_non_terminal() -> None:
    doc = _doc(("GHSA-69w3-r845-3855", "not_affected"))
    assert vex_gate.evaluate(DETECTION_BODY, doc) is True
