# Copyright (c) 2026 Microsoft Corporation. All rights reserved.
# SPDX-License-Identifier: MIT
name: probe untrusted-input-in-run
permissions: {}
on: issues
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "${{ github.event.issue.title }}"
