// Copyright (c) 2026 Microsoft Corporation. All rights reserved.
// SPDX-License-Identifier: MIT
import { test, expect, type Locator, type Page } from '@playwright/test';
// The sidebar configuration is the independent oracle for this spec. Deriving
// expectations from rendered DOM instead would be circular: the rendering is
// the thing under test, so a defect that dropped a category would also drop it
// from the expectation and the suite would stay green.
//
// The configuration names only explicit categories. Autogenerated directories
// contribute further categories from their subdirectories, so the rendered set
// is a superset of the configured set. Configured categories are therefore
// checked for presence, and every rendered category header is separately held
// to the shape rule below.
import sidebars from '../sidebars';
import { waitForHydration } from './_helpers/a11yInvariants';

const BASE = '/hve-core/docs/';
// Scoped to the docs sidebar's own theme class. The mobile drawer's primary
// panel reuses `.menu__list-item-collapsible` for navbar dropdown menus, which
// are a different control with different rules, so an unscoped selector would
// hold unrelated navbar items to this phase's category contract.
const CATEGORY_ITEM = 'li.theme-doc-sidebar-item-category';
const CATEGORY_HEADER = `${CATEGORY_ITEM} > .menu__list-item-collapsible`;
const CATEGORY_TOGGLE = `${CATEGORY_HEADER} > button`;

interface ExpectedCategory {
  /** Recursive label path, e.g. ["Workflows", "RPI Workflow"]. Unique per category. */
  path: string[];
  identity: string;
  label: string;
  /** Resolved landing route for a linked category, otherwise null. */
  landingRoute: string | null;
}

// Turns a category link document id into the route Docusaurus emits for it.
// Every landing document in this sidebar is a directory README, which renders
// at the directory route with a trailing slash.
function routeForDocId(id: string): string {
  return `${BASE}${id.replace(/\/README$/, '')}/`;
}

function collectExpectedCategories(
  items: readonly unknown[],
  ancestry: readonly string[] = [],
): ExpectedCategory[] {
  const found: ExpectedCategory[] = [];

  for (const raw of items) {
    const item = raw as {
      type?: string;
      label?: string;
      link?: { type?: string; id?: string };
      items?: readonly unknown[];
    };
    if (item?.type !== 'category' || typeof item.label !== 'string') {
      continue;
    }

    const path = [...ancestry, item.label];
    found.push({
      path,
      identity: path.join(' > '),
      label: item.label,
      landingRoute:
        item.link?.type === 'doc' && typeof item.link.id === 'string'
          ? routeForDocId(item.link.id)
          : null,
    });

    if (Array.isArray(item.items)) {
      found.push(...collectExpectedCategories(item.items, path));
    }
  }

  return found;
}

const EXPECTED_CATEGORIES = collectExpectedCategories(sidebars.docsSidebar as readonly unknown[]);
const LINKED_CATEGORIES = EXPECTED_CATEGORIES.filter((category) => category.landingRoute !== null);

// Category labels are short and repeat as substrings, so matching must be exact.
function exactLabel(label: string): RegExp {
  return new RegExp(`^${label.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}$`);
}

// Docusaurus derives its collapse duration from the expanding element's height
// (`getAutoHeightDuration` in theme-common's Collapsible), so the tall desktop
// sidebar animates several times longer than a short mobile drawer panel.
// Playwright waits for an element to stop moving before clicking it, so the
// exhaustive walks below spent most of their budget watching animations. Under
// reduced motion that duration drops to 1ms.
//
// This weakens nothing. Every assertion here is about structure, ARIA state,
// destinations, or computed outline width, and none observes motion. The
// drawer-persistence checks assert a state class rather than animated geometry
// for the same reason.
test.use({ contextOptions: { reducedMotion: 'reduce' } });

// Guards the oracle itself. If the sidebar config is ever restructured such
// that this parser silently returns nothing, every downstream check would
// trivially pass against an empty expectation.
test('sidebar configuration yields a non-trivial category inventory', () => {
  expect(EXPECTED_CATEGORIES.length).toBeGreaterThan(1);
  expect(LINKED_CATEGORIES.length).toBeGreaterThan(1);

  const identities = EXPECTED_CATEGORIES.map((category) => category.identity);
  expect(new Set(identities).size, 'category identities must be unique').toBe(identities.length);
});

// Opens each category along a label path, outermost first, and returns the
// deepest toggle.
//
// `autoCollapseCategories` is enabled, so opening a category collapses its
// siblings. Walking one ancestor path at a time cooperates with that behavior;
// holding the whole tree open at once would fight it and flake. Categories are
// also lazily rendered, so a descendant does not exist in the DOM until its
// ancestors are open, which is why each step is awaited before the next.
async function openCategoryPath(root: Locator, path: readonly string[]): Promise<Locator> {
  let toggle!: Locator;

  for (let depth = 0; depth < path.length; depth += 1) {
    toggle = root.locator(CATEGORY_TOGGLE).filter({ hasText: exactLabel(path[depth]) }).first();
    await expect(
      toggle,
      `category "${path.slice(0, depth + 1).join(' > ')}" should be present`,
    ).toBeVisible();

    if ((await toggle.getAttribute('aria-expanded')) === 'false') {
      await toggle.click();
      await expect(toggle).toHaveAttribute('aria-expanded', 'true');
    }
  }

  return toggle;
}

async function openMobileSidebar(page: Page): Promise<Locator> {
  const toggle = page.locator('.navbar__toggle');
  await expect(toggle).toBeVisible();
  await toggle.click();

  const drawer = page.locator('.navbar-sidebar');
  await expect(drawer).toBeVisible();

  // The drawer opens on its primary panel; the docs tree lives behind the
  // "Documentation" entry in the secondary panel.
  const docsEntry = drawer.getByRole('button', { name: /documentation/i }).first();
  if (await docsEntry.isVisible().catch(() => false)) {
    await docsEntry.click();
  }

  // The panel swap is a CSS transform transition, so the docs tree is present
  // in the DOM before it is visible. Waiting for a known category to be
  // visible, rather than for the drawer alone, keeps the later assertions from
  // racing the animation and reporting a settled control as hidden.
  await expect(
    drawer.locator(CATEGORY_TOGGLE).filter({ hasText: exactLabel('Get Started') }).first(),
  ).toBeVisible();

  return drawer;
}

const SURFACES = [
  {
    name: 'desktop',
    viewport: { width: 1280, height: 900 },
    async open(page: Page): Promise<Locator> {
      return page.locator('nav.menu');
    },
  },
  {
    name: 'mobile',
    viewport: { width: 390, height: 844 },
    open: openMobileSidebar,
  },
] as const;

for (const surface of SURFACES) {
  test.describe(`Sidebar category disclosure (${surface.name})`, () => {
    test.use({ viewport: surface.viewport });

    test('every configured category is present in the rendered tree', async ({ page }) => {
      // This test opens every configured category's own ancestor path in turn,
      // so its cost scales with the configuration rather than with a fixed
      // number of interactions. The default per-test budget is sized for a
      // handful of actions, not a full tree walk.
      test.setTimeout(60000);
      await page.goto(BASE);
      await waitForHydration(page);
      const root = await surface.open(page);

      // Presence is verified per configured category by opening its own
      // ancestor path, which is both lazy-safe and auto-collapse-safe.
      for (const category of EXPECTED_CATEGORIES) {
        await openCategoryPath(root, category.path);
      }
    });

    test('no category header renders a navigating link', async ({ page }) => {
      // Walks every configured category path, as above.
      test.setTimeout(60000);
      await page.goto(BASE);
      await waitForHydration(page);
      const root = await surface.open(page);

      // The defect this phase fixes was a category header that announced
      // expansion while behaving as a link. This is a universal property of
      // every rendered docs category header, so it also covers the
      // autogenerated categories the configuration never names.
      //
      // Shape is read in a single DOM pass rather than by index. Opening a
      // category collapses its siblings, so the header set changes between a
      // count and a later indexed lookup, and an index can resolve to nothing.
      for (const category of EXPECTED_CATEGORIES) {
        await openCategoryPath(root, category.path);

        const shapes = await root.evaluate((element) =>
          Array.from(
            element.querySelectorAll(
              'li.theme-doc-sidebar-item-category > .menu__list-item-collapsible',
            ),
          ).map((header) => ({
            label: header.textContent?.trim() ?? '',
            anchors: header.querySelectorAll(':scope > a').length,
            buttons: header.querySelectorAll(':scope > button').length,
          })),
        );

        expect(shapes.length).toBeGreaterThan(0);
        for (const shape of shapes) {
          expect(shape.anchors, `category header "${shape.label}" must not render a link`).toBe(0);
          expect(shape.buttons, `category header "${shape.label}" must render one button`).toBe(1);
        }
      }
    });

    test('category toggles expose disclosure state and no aria-controls', async ({ page }) => {
      await page.goto(BASE);
      await waitForHydration(page);
      const root = await surface.open(page);

      const toggles = root.locator(CATEGORY_TOGGLE);
      const total = await toggles.count();
      expect(total).toBeGreaterThan(0);

      for (let index = 0; index < total; index += 1) {
        const toggle = toggles.nth(index);
        await expect(toggle).toHaveAttribute('aria-expanded', /^(true|false)$/);
        // Omitted on purpose: `Collapsible lazy` renders no target for a
        // never-opened group, so any referenced id would dangle.
        await expect(toggle).not.toHaveAttribute('aria-controls', /.*/);
        // The name states the action and identifies which category it acts on.
        await expect(toggle).toHaveAccessibleName(/sidebar category/i);
      }
    });

    test('Enter and Space toggle a category without navigating', async ({ page }) => {
      await page.goto(BASE);
      await waitForHydration(page);
      const root = await surface.open(page);

      // Pinned to a named top-level category so sibling auto-collapse cannot
      // re-collapse the control under test while the assertions run.
      const toggle = root
        .locator(CATEGORY_TOGGLE)
        .filter({ hasText: exactLabel('Get Started') })
        .first();
      const urlBefore = page.url();

      await toggle.focus();
      const initial = await toggle.getAttribute('aria-expanded');
      const flipped = initial === 'true' ? 'false' : 'true';

      await page.keyboard.press('Enter');
      await expect(toggle).toHaveAttribute('aria-expanded', flipped);

      await page.keyboard.press('Space');
      await expect(toggle).toHaveAttribute('aria-expanded', initial ?? '');

      expect(page.url(), 'a disclosure control must not navigate').toBe(urlBefore);
    });

    test('every linked category exposes its landing page as its first child', async ({ page }) => {
      await page.goto(BASE);
      await waitForHydration(page);
      const root = await surface.open(page);

      for (const category of LINKED_CATEGORIES) {
        const toggle = await openCategoryPath(root, category.path);

        const firstChildHref = await toggle.evaluate((button) => {
          const list = button.closest('li')?.querySelector(':scope > ul.menu__list');
          const firstLink = list?.querySelector(':scope > li a[href]') as HTMLAnchorElement | null;
          return firstLink ? new URL(firstLink.href).pathname : null;
        });

        expect(
          firstChildHref,
          `category "${category.identity}" must expose ${category.landingRoute} as its first child`,
        ).toBe(category.landingRoute);
      }
    });
  });
}

// Lazy rendering is a deliberate retained behavior, not an accident. Asserting
// it keeps a future change from mounting every group eagerly on the assumption
// that nothing depended on the current lifecycle.
test.describe('Sidebar lazy rendering (desktop)', () => {
  test.use({ viewport: { width: 1280, height: 900 } });

  test('a collapsed category renders no child list until it is opened', async ({ page }) => {
    await page.goto(BASE);
    await waitForHydration(page);
    const root = page.locator('nav.menu');

    // Pinned to a named top-level category rather than "the first collapsed
    // one": sibling auto-collapse changes which categories are collapsed as
    // soon as one is clicked, so a positional locator would silently
    // re-resolve to a different element mid-test.
    const toggle = root.locator(CATEGORY_TOGGLE).filter({ hasText: exactLabel('Planning') }).first();
    await expect(toggle).toHaveAttribute('aria-expanded', 'false');

    const listItem = toggle.locator('xpath=ancestor::li[1]');
    await expect(listItem.locator('> ul.menu__list')).toHaveCount(0);

    await toggle.click();
    await expect(toggle).toHaveAttribute('aria-expanded', 'true');
    await expect(listItem.locator('> ul.menu__list')).toHaveCount(1);
  });
});

test.describe('Sidebar toggle focus indication (desktop)', () => {
  test.use({ viewport: { width: 1280, height: 900 } });

  test('a focused category toggle has a visible focus indicator', async ({ page }) => {
    await page.goto(BASE);
    await waitForHydration(page);

    const toggle = page.locator(`nav.menu ${CATEGORY_TOGGLE}`).first();
    await toggle.focus();

    const outlineWidth = await toggle.evaluate((element) => getComputedStyle(element).outlineWidth);
    expect(parseFloat(outlineWidth)).toBeGreaterThanOrEqual(2);
  });
});

test.describe('Sidebar toggle focus indication (forced colors)', () => {
  test.use({
    viewport: { width: 1280, height: 900 },
    contextOptions: { forcedColors: 'active' },
  });

  test('a focused category toggle keeps an outline in forced-colors mode', async ({ page }) => {
    await page.goto(BASE);
    await waitForHydration(page);

    const emulationActive = await page.evaluate(
      () => window.matchMedia('(forced-colors: active)').matches,
    );
    expect(emulationActive, 'forced-colors emulation must be in effect').toBe(true);

    const toggle = page.locator(`nav.menu ${CATEGORY_TOGGLE}`).first();
    await toggle.focus();

    // Asserted at 3px, not 2px, because that is what the forced-colors rule
    // uniquely contributes. The normal focus rule already supplies a 2px
    // outline that survives forced-colors mode, so a 2px threshold would keep
    // passing even if the forced-colors rule were deleted, and this test would
    // guard nothing. Forced-colors also drops the box-shadow half of the normal
    // dual-band indicator, which is why a dedicated rule exists at all.
    const outlineWidth = await toggle.evaluate((element) => getComputedStyle(element).outlineWidth);
    expect(parseFloat(outlineWidth)).toBeGreaterThanOrEqual(3);
  });
});

// The mobile drawer closes when a child link navigates, which is correct. It
// must not close when a category is merely disclosed, because the user has not
// gone anywhere and would lose their place in the tree.
//
// Both a linked and an unlinked category are exercised. Upstream's mobile
// callback only closes the drawer for a category that carries an `href`, so a
// test that toggled an unlinked category alone would never reach the branch
// that can regress.
test.describe('Mobile drawer persistence', () => {
  test.use({ viewport: { width: 390, height: 844 } });

  for (const { label, linked } of [
    { label: 'Get Started', linked: true },
    { label: 'Workflows', linked: false },
  ]) {
    test(`toggling the ${linked ? 'linked' : 'unlinked'} category "${label}" leaves the mobile drawer open`, async ({
      page,
    }) => {
      await page.goto(BASE);
      await waitForHydration(page);
      const drawer = await openMobileSidebar(page);

      const toggle = drawer.locator(CATEGORY_TOGGLE).filter({ hasText: exactLabel(label) }).first();
      await expect(toggle).toBeVisible();

      const initial = await toggle.getAttribute('aria-expanded');
      const flipped = initial === 'true' ? 'false' : 'true';
      await toggle.click();

      // Wait for the disclosure state to commit first. Closing the drawer and
      // flipping this attribute are both React state updates from the same
      // click, so once this is observable the drawer's own state has committed
      // too. Asserting drawer visibility directly would be vacuous: the drawer
      // closes through a CSS transform transition and is still visible for the
      // first frames, so the assertion would pass before the close took effect.
      await expect(toggle).toHaveAttribute('aria-expanded', flipped);

      // The state class, not the animated geometry, is what says the drawer is
      // open.
      await expect(page.locator('.navbar')).toHaveClass(/navbar-sidebar--show/);
      await expect(drawer).toBeVisible();
    });
  }
});
