ARG BASE_IMAGE=mcr.microsoft.com/devcontainers/base:2-jammy
FROM ${BASE_IMAGE}

ARG NPM_CONFIG_REGISTRY=https://registry.npmjs.org/
ENV NPM_CONFIG_REGISTRY=${NPM_CONFIG_REGISTRY}

ARG PIP_INDEX_URL=https://pypi.org/simple/
ENV PIP_INDEX_URL=${PIP_INDEX_URL}

ARG UV_DEFAULT_INDEX=https://pypi.org/simple/
ENV UV_DEFAULT_INDEX=${UV_DEFAULT_INDEX}
