# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: MIT

# Test-FsiSustainabilityProfile.ps1
#
# Purpose: Sustainability-specific FSI validator. Enforces five rules over
#          bundles under .github/skills/sustainability/ plus DD-13 inline
#          disclaimer-string assertions over emitted artifacts under
#          .copilot-tracking/sustainability-plans/. Designed to be invoked by
#          Validate-FsiContent.ps1 (Step 4.3 / DD-06) and standalone.

#Requires -Version 7.0

[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [string]$RepoRoot,

    [Parameter(Mandatory = $false)]
    [string]$SustainabilitySkillsPath = '.github/skills/sustainability',

    [Parameter(Mandatory = $false)]
    [string]$DisclaimerInstructionsPath = '.github/instructions/shared/disclaimer-language.instructions.md',

    [Parameter(Mandatory = $false)]
    [string]$PlansRoot = '.copilot-tracking/sustainability-plans',

    [Parameter(Mandatory = $false)]
    [string[]]$ArtifactPaths = @(),

    [Parameter(Mandatory = $false)]
    [string[]]$SkillsLoadedLogPaths = @(),

    [Parameter(Mandatory = $false)]
    [string]$ExpectedDisclaimerHash,

    [Parameter(Mandatory = $false)]
    [switch]$AsObject
)

$ErrorActionPreference = 'Stop'

if (-not $RepoRoot) {
    $RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '../..')).ProviderPath
}

Import-Module 'powershell-yaml' -Force -ErrorAction Stop | Out-Null

# ----- Constants ---------------------------------------------------------

$script:AllowedLicenses = @(
    'CSL-1.0',
    'Apache-2.0',
    'CC-BY-4.0',
    'W3C-CFSA',
    'MIT',
    'Apache-2.0+CC-BY-4.0',
    'CC-BY-4.0+MIT'
)

$script:AttributionRequiredLicenses = @('CSL-1.0', 'CC-BY-4.0', 'W3C-CFSA')

$script:RuntimeFetchAttributionMarkers = @('Electricity Maps', 'WattTime API')

$script:BacklogFooter = '> Directional sustainability estimate produced by an AI planner. Not an audited disclosure. Review by a qualified sustainability professional and applicable disclosure-framework counsel (CSRD/ESRS, SEC climate rules, GHG Protocol, TCFD, ISO 14064/14067) is required before external use.'

$script:ActiveControlsDisclaimer = 'Directional sustainability estimate produced by an AI planner. Not an audited disclosure. Review by a qualified sustainability professional and applicable disclosure-framework counsel (CSRD/ESRS, SEC climate rules, GHG Protocol, TCFD, ISO 14064/14067) is required before external use.'

$script:SciBudgetsHeader = @(
    '# Directional SCI estimate (gCO2eq, per functional unit) generated by an AI planner.',
    '# Measurement-class precedence: deterministic > estimated > heuristic > user-declared.',
    '# Not an audited disclosure; review by qualified sustainability and disclosure-framework counsel required before external use.'
) -join "`n"

$script:PptxFooterShortHook = 'Directional estimate. Not an audited disclosure.'

# ----- Helpers -----------------------------------------------------------

function New-Diagnostic {
    param(
        [Parameter(Mandatory)] [ValidateSet('error', 'warning')] [string]$Severity,
        [Parameter(Mandatory)] [string]$Rule,
        [Parameter(Mandatory)] [string]$Message,
        [Parameter()] [string]$Path
    )
    [pscustomobject]@{
        severity = $Severity
        rule     = $Rule
        message  = $Message
        path     = $Path
    }
}

function Get-RelativePath {
    param([string]$Path)
    if ([string]::IsNullOrWhiteSpace($Path)) { return $Path }
    return [System.IO.Path]::GetRelativePath($RepoRoot, $Path)
}

function Read-YamlFile {
    param([Parameter(Mandatory)] [string]$Path)
    try {
        $raw = Get-Content -LiteralPath $Path -Raw -Encoding utf8
        return ConvertFrom-Yaml -Yaml $raw -ErrorAction Stop
    } catch {
        return $null
    }
}

# ----- Rule 1: License whitelist -----------------------------------------

function Test-SustainabilityLicenseWhitelist {
    [OutputType([pscustomobject[]])]
    param([Parameter(Mandatory)] [string]$BundleRoot)

    $diagnostics = @()
    $manifestPath = Join-Path $BundleRoot 'index.yml'
    if (-not (Test-Path -LiteralPath $manifestPath -PathType Leaf)) {
        $diagnostics += New-Diagnostic -Severity error -Rule 'license-whitelist' `
            -Message "Bundle missing index.yml" -Path (Get-RelativePath $BundleRoot)
        return $diagnostics
    }

    $manifest = Read-YamlFile -Path $manifestPath
    if ($null -eq $manifest -or -not ($manifest -is [System.Collections.IDictionary])) {
        $diagnostics += New-Diagnostic -Severity error -Rule 'license-whitelist' `
            -Message 'index.yml could not be parsed as a YAML mapping' `
            -Path (Get-RelativePath $manifestPath)
        return $diagnostics
    }

    $metadata = $manifest['metadata']
    if ($null -eq $metadata -or -not ($metadata -is [System.Collections.IDictionary])) {
        $diagnostics += New-Diagnostic -Severity error -Rule 'license-whitelist' `
            -Message 'index.yml is missing the metadata block' `
            -Path (Get-RelativePath $manifestPath)
        return $diagnostics
    }

    $license = [string]$metadata['license']
    if ([string]::IsNullOrWhiteSpace($license)) {
        $diagnostics += New-Diagnostic -Severity error -Rule 'license-whitelist' `
            -Message 'metadata.license is missing or empty' `
            -Path (Get-RelativePath $manifestPath)
    } elseif ($script:AllowedLicenses -notcontains $license) {
        $diagnostics += New-Diagnostic -Severity error -Rule 'license-whitelist' `
            -Message "metadata.license '$license' is not in the sustainability whitelist ($($script:AllowedLicenses -join ', '))" `
            -Path (Get-RelativePath $manifestPath)
    }

    return , $diagnostics
}

# ----- Rule 2: Runtime-fetch ban (no embedded carbon-intensity literals) --

function Test-SustainabilityRuntimeFetchBan {
    [OutputType([pscustomobject[]])]
    param([Parameter(Mandatory)] [string]$BundleRoot)

    $diagnostics = @()
    $itemsDir = Join-Path $BundleRoot 'items'
    if (-not (Test-Path -LiteralPath $itemsDir -PathType Container)) {
        return , $diagnostics
    }

    $itemFiles = Get-ChildItem -LiteralPath $itemsDir -Filter '*.yml' -File -ErrorAction SilentlyContinue
    foreach ($itemFile in $itemFiles) {
        $item = Read-YamlFile -Path $itemFile.FullName
        if ($null -eq $item) { continue }

        $controls = @()
        if ($item -is [System.Collections.IDictionary] -and $item.ContainsKey('controls')) {
            $controls = @($item['controls'])
        } elseif ($item -is [System.Collections.IDictionary]) {
            $controls = @($item)
        }

        foreach ($ctrl in $controls) {
            if ($ctrl -isnot [System.Collections.IDictionary]) { continue }
            $controlId = if ($ctrl.ContainsKey('id')) { [string]$ctrl['id'] } else { '<unknown>' }
            $body = if ($ctrl.ContainsKey('body')) { [string]$ctrl['body'] } else { '' }
            $references = if ($ctrl.ContainsKey('references')) { @($ctrl['references']) } else { @() }

            $hasNumericLiteral = $body -match '\b\d+(\.\d+)?\s*(gCO2eq|gCO2|gco2eq|kgCO2|kWh|MWh|kw|kW|MW|tCO2)\b'
            if (-not $hasNumericLiteral) { continue }

            foreach ($ref in $references) {
                if ($ref -isnot [System.Collections.IDictionary]) { continue }
                $attr = if ($ref.ContainsKey('attribution')) { [string]$ref['attribution'] } else { '' }
                foreach ($marker in $script:RuntimeFetchAttributionMarkers) {
                    if ($attr -match [regex]::Escape($marker)) {
                        $diagnostics += New-Diagnostic -Severity error -Rule 'runtime-fetch-ban' `
                            -Message "control '$controlId' embeds a numeric carbon-intensity literal sourced from '$marker'; runtime fetch only" `
                            -Path (Get-RelativePath $itemFile.FullName)
                    }
                }
            }
        }
    }

    return , $diagnostics
}

# ----- Rule 3: Attribution required for CSL-1.0 / CC-BY-4.0 / W3C-CFSA ---

function Test-SustainabilityAttributionRequired {
    [OutputType([pscustomobject[]])]
    param([Parameter(Mandatory)] [string]$BundleRoot)

    $diagnostics = @()
    $manifestPath = Join-Path $BundleRoot 'index.yml'
    if (-not (Test-Path -LiteralPath $manifestPath -PathType Leaf)) { return , $diagnostics }

    $manifest = Read-YamlFile -Path $manifestPath
    if ($null -eq $manifest -or -not ($manifest -is [System.Collections.IDictionary])) {
        return , $diagnostics
    }
    $metadata = $manifest['metadata']
    if ($null -eq $metadata -or -not ($metadata -is [System.Collections.IDictionary])) {
        return , $diagnostics
    }

    $license = [string]$metadata['license']
    $licenseTokens = $license -split '\+' | ForEach-Object { $_.Trim() }
    $needsAttribution = $false
    foreach ($token in $licenseTokens) {
        if ($script:AttributionRequiredLicenses -contains $token) { $needsAttribution = $true }
    }
    if (-not $needsAttribution) { return , $diagnostics }

    $attributionRequired = $false
    if ($metadata.ContainsKey('attributionRequired')) {
        $attributionRequired = [bool]$metadata['attributionRequired']
    }
    $attributionText = if ($metadata.ContainsKey('attributionText')) { [string]$metadata['attributionText'] } else { '' }

    if (-not $attributionRequired) {
        $diagnostics += New-Diagnostic -Severity error -Rule 'attribution-required' `
            -Message "license '$license' requires metadata.attributionRequired: true" `
            -Path (Get-RelativePath $manifestPath)
    }
    if ([string]::IsNullOrWhiteSpace($attributionText)) {
        $diagnostics += New-Diagnostic -Severity error -Rule 'attribution-required' `
            -Message "license '$license' requires non-empty metadata.attributionText" `
            -Path (Get-RelativePath $manifestPath)
    }

    return , $diagnostics
}

# ----- Rule 4: Append-only skills-loaded.log ----------------------------

function Test-SustainabilitySkillsLoadedLogAppendOnly {
    [OutputType([pscustomobject[]])]
    param([Parameter(Mandatory)] [string]$LogPath)

    $diagnostics = @()
    if (-not (Test-Path -LiteralPath $LogPath -PathType Leaf)) {
        $diagnostics += New-Diagnostic -Severity error -Rule 'skills-loaded-log-append-only' `
            -Message 'skills-loaded.log is missing' -Path (Get-RelativePath $LogPath)
        return , $diagnostics
    }

    $lines = Get-Content -LiteralPath $LogPath -Encoding utf8 -ErrorAction SilentlyContinue
    if ($null -eq $lines) { return , $diagnostics }

    $previousTimestamp = $null
    $lineNumber = 0
    foreach ($line in $lines) {
        $lineNumber++
        if ([string]::IsNullOrWhiteSpace($line)) { continue }
        $fields = $line -split "`t"
        if ($fields.Count -lt 5) {
            $diagnostics += New-Diagnostic -Severity error -Rule 'skills-loaded-log-append-only' `
                -Message "line ${lineNumber}: expected 5 tab-separated fields (ISO8601, bundleId, version, license, attributionRequired)" `
                -Path (Get-RelativePath $LogPath)
            continue
        }
        [datetime]$timestamp = [datetime]::MinValue
        if (-not [datetime]::TryParse($fields[0], [ref]$timestamp)) {
            $diagnostics += New-Diagnostic -Severity error -Rule 'skills-loaded-log-append-only' `
                -Message "line ${lineNumber}: first field '$($fields[0])' is not a parseable ISO-8601 timestamp" `
                -Path (Get-RelativePath $LogPath)
            continue
        }
        if ($null -ne $previousTimestamp -and $timestamp -lt $previousTimestamp) {
            $diagnostics += New-Diagnostic -Severity error -Rule 'skills-loaded-log-append-only' `
                -Message "line ${lineNumber}: timestamp '$($fields[0])' is earlier than the prior line; append-only invariant broken" `
                -Path (Get-RelativePath $LogPath)
        }
        $previousTimestamp = $timestamp
    }
    return , $diagnostics
}

# ----- Rule 5: Disclaimer drift hash-check ------------------------------

function Get-SustainabilityDisclaimerHash {
    [OutputType([string])]
    param([Parameter(Mandatory)] [string]$DisclaimerFilePath)

    if (-not (Test-Path -LiteralPath $DisclaimerFilePath -PathType Leaf)) { return $null }
    $content = Get-Content -LiteralPath $DisclaimerFilePath -Raw -Encoding utf8

    # Extract the '## Sustainability Planning' block up to the next H2 (^## ) or EOF.
    $pattern = '(?ms)^##[ \t]+Sustainability Planning[ \t]*\r?\n(.*?)(?=^##[ \t]|\z)'
    $match = [regex]::Match($content, $pattern)
    if (-not $match.Success) { return $null }

    $block = $match.Groups[1].Value
    # Pull the [!CAUTION] callout block: lines starting with '> '.
    $callout = ($block -split "`n" | Where-Object { $_ -match '^\s*>' }) -join "`n"
    if ([string]::IsNullOrWhiteSpace($callout)) { $callout = $block }

    $bytes = [System.Text.Encoding]::UTF8.GetBytes($callout.Trim())
    $sha = [System.Security.Cryptography.SHA256]::Create()
    try {
        $hashBytes = $sha.ComputeHash($bytes)
        return -join ($hashBytes | ForEach-Object { $_.ToString('x2') })
    } finally {
        $sha.Dispose()
    }
}

function Test-SustainabilityDisclaimerHash {
    [OutputType([pscustomobject[]])]
    param(
        [Parameter(Mandatory)] [string]$DisclaimerFilePath,
        [Parameter()] [string]$ExpectedHash
    )
    $diagnostics = @()
    $actual = Get-SustainabilityDisclaimerHash -DisclaimerFilePath $DisclaimerFilePath
    if ($null -eq $actual) {
        # Pre-Phase-5 state: the '## Sustainability Planning' block has not yet
        # been added to the shared disclaimer file. Emit a warning so the lint
        # remains visible but does not break validation until Step 5.10 lands.
        $diagnostics += New-Diagnostic -Severity warning -Rule 'disclaimer-drift' `
            -Message "'## Sustainability Planning' [!CAUTION] block not present (pending Step 5.10)" `
            -Path (Get-RelativePath $DisclaimerFilePath)
        return , $diagnostics
    }
    if (-not [string]::IsNullOrWhiteSpace($ExpectedHash) -and $actual -ne $ExpectedHash) {
        $diagnostics += New-Diagnostic -Severity error -Rule 'disclaimer-drift' `
            -Message "disclaimer SHA-256 mismatch: expected '$ExpectedHash', actual '$actual'" `
            -Path (Get-RelativePath $DisclaimerFilePath)
    }
    return , $diagnostics
}

# ----- DD-13 inline-string assertions ------------------------------------

function Test-SustainabilityInlineDisclaimer {
    [OutputType([pscustomobject[]])]
    param([Parameter(Mandatory)] [string]$ArtifactPath)

    $diagnostics = @()
    if (-not (Test-Path -LiteralPath $ArtifactPath -PathType Leaf)) {
        return , $diagnostics
    }
    $rel = Get-RelativePath $ArtifactPath
    $name = [System.IO.Path]::GetFileName($ArtifactPath)
    $ext = [System.IO.Path]::GetExtension($ArtifactPath).ToLowerInvariant()

    $isBacklogItem = ($rel -match '/sustainability-plans/[^/]+/backlog/.+\.md$') -and ($ext -eq '.md')
    $isActiveControls = ($name -ieq 'active-controls.json')
    $isSciBudget = ($rel -match '/sustainability-plans/[^/]+/sci-budgets/.+\.ya?ml$')
    $isPptx = ($ext -eq '.pptx')

    if ($isBacklogItem) {
        $content = Get-Content -LiteralPath $ArtifactPath -Raw -Encoding utf8
        $trimmed = $content.TrimEnd()
        if (-not $trimmed.EndsWith($script:BacklogFooter)) {
            $diagnostics += New-Diagnostic -Severity error -Rule 'inline-disclaimer-backlog-footer' `
                -Message "backlog item must end with the verbatim footer line; missing or altered footer" `
                -Path $rel
        }
    } elseif ($isActiveControls) {
        try {
            $obj = Get-Content -LiteralPath $ArtifactPath -Raw -Encoding utf8 | ConvertFrom-Json -ErrorAction Stop
            $disc = $obj.disclaimer
            if ([string]::IsNullOrWhiteSpace($disc) -or $disc -ne $script:ActiveControlsDisclaimer) {
                $diagnostics += New-Diagnostic -Severity error -Rule 'inline-disclaimer-active-controls' `
                    -Message "active-controls.json must contain a top-level 'disclaimer' field equal to the verbatim sentence" `
                    -Path $rel
            }
        } catch {
            $diagnostics += New-Diagnostic -Severity error -Rule 'inline-disclaimer-active-controls' `
                -Message "active-controls.json is not parseable JSON: $($_.Exception.Message)" `
                -Path $rel
        }
    } elseif ($isSciBudget) {
        $content = Get-Content -LiteralPath $ArtifactPath -Raw -Encoding utf8
        $normalized = $content -replace "`r`n", "`n"
        if (-not $normalized.StartsWith($script:SciBudgetsHeader)) {
            $diagnostics += New-Diagnostic -Severity error -Rule 'inline-disclaimer-sci-budgets-header' `
                -Message "sci-budgets file must begin with the verbatim 3-line header comment block" `
                -Path $rel
        }
    } elseif ($isPptx) {
        # Binary inspection: read raw bytes and substring-match the short hook.
        $bytes = [System.IO.File]::ReadAllBytes($ArtifactPath)
        $text = [System.Text.Encoding]::UTF8.GetString($bytes)
        if ($text -notmatch [regex]::Escape($script:PptxFooterShortHook)) {
            $diagnostics += New-Diagnostic -Severity error -Rule 'inline-disclaimer-pptx-footer' `
                -Message "PPTX must contain the verbatim short hook in a footer text frame" `
                -Path $rel
        }
    }

    return , $diagnostics
}

# ----- Orchestration -----------------------------------------------------

function Invoke-FsiSustainabilityProfile {
    [OutputType([pscustomobject])]
    param()

    $allDiagnostics = @()
    $skillsRoot = Join-Path $RepoRoot $SustainabilitySkillsPath

    if (Test-Path -LiteralPath $skillsRoot -PathType Container) {
        $bundles = Get-ChildItem -LiteralPath $skillsRoot -Directory -ErrorAction SilentlyContinue
        foreach ($bundle in $bundles) {
            $allDiagnostics += @(Test-SustainabilityLicenseWhitelist -BundleRoot $bundle.FullName)
            $allDiagnostics += @(Test-SustainabilityRuntimeFetchBan -BundleRoot $bundle.FullName)
            $allDiagnostics += @(Test-SustainabilityAttributionRequired -BundleRoot $bundle.FullName)
        }
    }

    $disclaimerPath = Join-Path $RepoRoot $DisclaimerInstructionsPath
    $allDiagnostics += @(Test-SustainabilityDisclaimerHash -DisclaimerFilePath $disclaimerPath -ExpectedHash $ExpectedDisclaimerHash)

    foreach ($logPath in $SkillsLoadedLogPaths) {
        $allDiagnostics += @(Test-SustainabilitySkillsLoadedLogAppendOnly -LogPath $logPath)
    }

    foreach ($artifact in $ArtifactPaths) {
        $allDiagnostics += @(Test-SustainabilityInlineDisclaimer -ArtifactPath $artifact)
    }

    $allDiagnostics = @($allDiagnostics | Where-Object { $null -ne $_ -and $_.severity })
    $errors = @($allDiagnostics | Where-Object { $_.severity -eq 'error' })
    $warnings = @($allDiagnostics | Where-Object { $_.severity -eq 'warning' })

    return [pscustomobject]@{
        ErrorCount    = $errors.Count
        WarningCount  = $warnings.Count
        Diagnostics   = $allDiagnostics
    }
}

# ----- Entry point -------------------------------------------------------

if ($MyInvocation.InvocationName -ne '.') {
    $result = Invoke-FsiSustainabilityProfile
    if ($AsObject) {
        $result
    } else {
        foreach ($d in $result.Diagnostics) {
            $prefix = if ($d.severity -eq 'error') { 'ERROR' } else { 'WARN ' }
            $loc = if ($d.path) { " [$($d.path)]" } else { '' }
            Write-Host "$prefix $($d.rule): $($d.message)$loc"
        }
        Write-Host ""
        Write-Host "Sustainability profile: $($result.ErrorCount) error(s), $($result.WarningCount) warning(s)."
        if ($result.ErrorCount -gt 0) { exit 1 } else { exit 0 }
    }
}
