name: Weekly GitHub Code Scanning

on:
  schedule:
    - cron: '0 3 * * 1' # Mondays at 03:00 UTC
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read
  issues: write
  security-events: read

jobs:
  gh-code-scanning:
    name: GitHub Code Scanning
    uses: ./.github/workflows/gh-code-scanning.yml
    permissions:
      contents: read
      security-events: read

  create-gh-code-scanning-issues:
    name: Create GitHub Code Scanning Issues
    needs: [gh-code-scanning]
    uses: ./.github/workflows/create-gh-code-scanning-issues.yml
    permissions:
      issues: write
      security-events: read
